services:
  
type: web
  name: data-collector-server
  runtime: python
  repo: https://github.com/codap0p/rat.L
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn server:app
  envVars:
key: PYTHON_VERSION
    value: 3.11.0
healthCheckPath: /health
autoDeploy: true
